"""removed title and description from submission

Revision ID: 14602e2819f5
Revises: 3069d5940d4e
Create Date: 2024-03-10 22:03:40.128491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14602e2819f5'
down_revision: Union[str, None] = '3069d5940d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'description')
    op.drop_column('submissions', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
