"""removed max group size

Revision ID: 3069d5940d4e
Revises: 7e3483a3acde
Create Date: 2024-03-10 12:36:09.813966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3069d5940d4e'
down_revision: Union[str, None] = '7e3483a3acde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hackathons', 'max_group_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackathons', sa.Column('max_group_size', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
