"""Added ondelete to foreign keys

Revision ID: 7e3483a3acde
Revises: e8d1f2cb4c18
Create Date: 2024-03-09 08:24:57.339364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e3483a3acde'
down_revision: Union[str, None] = 'e8d1f2cb4c18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hackathons_organizer_id_fkey', 'hackathons', type_='foreignkey')
    op.create_foreign_key(None, 'hackathons', 'users', ['organizer_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('participants_hackathon_id_fkey', 'participants', type_='foreignkey')
    op.create_foreign_key(None, 'participants', 'hackathons', ['hackathon_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('prizes_hackathon_id_fkey', 'prizes', type_='foreignkey')
    op.create_foreign_key(None, 'prizes', 'hackathons', ['hackathon_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('project_images_project_id_fkey', 'project_images', type_='foreignkey')
    op.create_foreign_key(None, 'project_images', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('project_members_user_id_fkey', 'project_members', type_='foreignkey')
    op.drop_constraint('project_members_project_id_fkey', 'project_members', type_='foreignkey')
    op.create_foreign_key(None, 'project_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_members', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('project_tags_tag_id_fkey', 'project_tags', type_='foreignkey')
    op.drop_constraint('project_tags_project_id_fkey', 'project_tags', type_='foreignkey')
    op.create_foreign_key(None, 'project_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_tags', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('projects_author_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.add_column('submissions', sa.Column('project_id', sa.Integer(), nullable=True))
    op.drop_constraint('submissions_hackathon_id_fkey', 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'hackathons', ['hackathon_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'submissions', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('winners_submission_id_fkey', 'winners', type_='foreignkey')
    op.drop_constraint('winners_project_id_fkey', 'winners', type_='foreignkey')
    op.drop_constraint('winners_prize_id_fkey', 'winners', type_='foreignkey')
    op.create_foreign_key(None, 'winners', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'winners', 'prizes', ['prize_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'winners', 'submissions', ['submission_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'winners', type_='foreignkey')
    op.drop_constraint(None, 'winners', type_='foreignkey')
    op.drop_constraint(None, 'winners', type_='foreignkey')
    op.create_foreign_key('winners_prize_id_fkey', 'winners', 'prizes', ['prize_id'], ['id'])
    op.create_foreign_key('winners_project_id_fkey', 'winners', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('winners_submission_id_fkey', 'winners', 'submissions', ['submission_id'], ['id'])
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key('submissions_hackathon_id_fkey', 'submissions', 'hackathons', ['hackathon_id'], ['id'])
    op.drop_column('submissions', 'project_id')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_author_id_fkey', 'projects', 'users', ['author_id'], ['id'])
    op.drop_constraint(None, 'project_tags', type_='foreignkey')
    op.drop_constraint(None, 'project_tags', type_='foreignkey')
    op.create_foreign_key('project_tags_project_id_fkey', 'project_tags', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('project_tags_tag_id_fkey', 'project_tags', 'tags', ['tag_id'], ['id'])
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.create_foreign_key('project_members_project_id_fkey', 'project_members', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('project_members_user_id_fkey', 'project_members', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'project_images', type_='foreignkey')
    op.create_foreign_key('project_images_project_id_fkey', 'project_images', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'prizes', type_='foreignkey')
    op.create_foreign_key('prizes_hackathon_id_fkey', 'prizes', 'hackathons', ['hackathon_id'], ['id'])
    op.drop_constraint(None, 'participants', type_='foreignkey')
    op.create_foreign_key('participants_hackathon_id_fkey', 'participants', 'hackathons', ['hackathon_id'], ['id'])
    op.drop_constraint(None, 'hackathons', type_='foreignkey')
    op.create_foreign_key('hackathons_organizer_id_fkey', 'hackathons', 'users', ['organizer_id'], ['id'])
    # ### end Alembic commands ###
