"""added ban field in submission and participant

Revision ID: 9cc3417fcd67
Revises: 14602e2819f5
Create Date: 2024-03-11 10:23:50.946463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cc3417fcd67'
down_revision: Union[str, None] = '14602e2819f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('baned', sa.Boolean(), nullable=True))
    op.add_column('submissions', sa.Column('baned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'baned')
    op.drop_column('participants', 'baned')
    # ### end Alembic commands ###
