"""default value for baned

Revision ID: e8d1f2cb4c18
Revises: 2e60ee10292e
Create Date: 2024-03-07 18:25:17.494188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8d1f2cb4c18'
down_revision: Union[str, None] = '2e60ee10292e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'baned', server_default=sa.sql.expression.false())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'baned', server_default=None)
    # ### end Alembic commands ###
